import { Terminal } from "lucide-react";
import type { Topic } from "../types";
import { linuxTutor } from "../prompts/linux-tutor";

export const linuxTopic: Topic = {
  id: "linux",
  slug: "linux",
  name: "Linux & Bash / לינוקס",
  description: "From your first `ls` to production-ready Bash scripts.",
  track: "devops",
  icon: Terminal,
  accent: {
    gradient: "from-gray-700 to-emerald-500",
    text: "text-emerald-600",
    ring: "ring-emerald-500/30",
  },
  tutor: linuxTutor,
  modules: [
    {
      id: "lx-intro",
      title: "What is Linux",
      emoji: "🐧",
      description: "Kernel vs. distro, why DevOps lives here.",
      lessons: [
        {
          id: "lx-intro-01",
          level: "beginner",
          title: "Kernel, distro, shell",
          description: "The pieces of a Linux system.",
          objectives: [
            "Distinguish kernel from distro",
            "Name 3 common distros",
            "Explain shell vs. terminal",
          ],
          keyTerms: ["kernel", "distro", "shell", "terminal", "Bash"],
          practiceQuestions: 3,
        },
      ],
    },
    {
      id: "lx-terminal",
      title: "Terminal Basics",
      emoji: "⌨️",
      description: "Your first commands.",
      lessons: [
        {
          id: "lx-term-01",
          level: "beginner",
          title: "pwd, ls, cd",
          description: "Moving around and looking at files.",
          objectives: [
            "Navigate the filesystem",
            "List files including hidden",
            "Read the man page for a command",
          ],
          keyTerms: ["pwd", "ls", "cd", "man", "--help"],
          practiceQuestions: 5,
        },
        {
          id: "lx-term-02",
          level: "beginner",
          title: "Help, history, autocomplete",
          description: "Becoming fast in the shell.",
          objectives: [
            "Use Tab completion",
            "Recall commands with ↑ and history",
            "Search history with Ctrl-R",
          ],
          keyTerms: ["history", "Tab", "Ctrl-R"],
          practiceQuestions: 3,
        },
      ],
    },
    {
      id: "lx-fs",
      title: "File System",
      emoji: "📂",
      description: "How Linux organises files.",
      lessons: [
        {
          id: "lx-fs-01",
          level: "beginner",
          title: "The directory tree",
          description: "/, /home, /etc, /var, /tmp.",
          objectives: [
            "Name the main top-level directories",
            "Explain the purpose of /etc and /var",
            "Distinguish absolute vs. relative paths",
          ],
          keyTerms: ["/", "/home", "/etc", "/var", "absolute", "relative"],
          practiceQuestions: 4,
        },
        {
          id: "lx-fs-02",
          level: "beginner",
          title: "cp, mv, rm, mkdir",
          description: "Creating, moving, deleting.",
          objectives: [
            "Copy and move files safely",
            "Delete with confidence (and caution)",
            "Use -r / -f flags responsibly",
          ],
          keyTerms: ["cp", "mv", "rm", "mkdir", "-r"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "lx-perm",
      title: "Permissions",
      emoji: "🔐",
      description: "rwx, users, groups, sudo.",
      lessons: [
        {
          id: "lx-perm-01",
          level: "intermediate",
          title: "rwx and chmod",
          description: "Read/write/execute for user/group/other.",
          objectives: [
            "Read an `ls -la` permission string",
            "Apply chmod in octal and symbolic form",
            "Explain why 777 is usually wrong",
          ],
          keyTerms: ["chmod", "rwx", "octal", "ls -la"],
          practiceQuestions: 5,
        },
        {
          id: "lx-perm-02",
          level: "intermediate",
          title: "Users, groups, sudo",
          description: "Who can do what.",
          objectives: [
            "List users and groups",
            "Change ownership with chown",
            "Use sudo safely",
          ],
          keyTerms: ["chown", "sudo", "/etc/passwd", "groups"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "lx-bash",
      title: "Bash Scripting",
      emoji: "📜",
      description: "From one-liners to full scripts.",
      lessons: [
        {
          id: "lx-bash-01",
          level: "intermediate",
          title: "Variables & quoting",
          description: "VAR=value, \"$VAR\", 'literal'.",
          objectives: [
            "Declare and expand variables",
            "Use single vs. double quotes correctly",
            "Understand command substitution $()",
          ],
          keyTerms: ["$VAR", "\"\"", "''", "$(...)", "shebang"],
          practiceQuestions: 5,
        },
        {
          id: "lx-bash-02",
          level: "advanced",
          title: "if / for / while and exit codes",
          description: "Control flow in Bash.",
          objectives: [
            "Write an if that checks $?",
            "Iterate over files in a directory",
            "Exit with meaningful codes",
          ],
          keyTerms: ["if", "for", "while", "exit", "$?"],
          practiceQuestions: 5,
        },
      ],
    },
    {
      id: "lx-proc",
      title: "Processes",
      emoji: "⚙️",
      description: "What's running on the box.",
      lessons: [
        {
          id: "lx-proc-01",
          level: "intermediate",
          title: "ps, top, kill",
          description: "Inspect and manage processes.",
          objectives: [
            "Find a PID",
            "Kill a runaway process",
            "Read top's columns",
          ],
          keyTerms: ["ps", "top", "kill", "PID", "htop"],
          practiceQuestions: 4,
        },
        {
          id: "lx-proc-02",
          level: "advanced",
          title: "systemd & journalctl",
          description: "Services on modern Linux.",
          objectives: [
            "Start / stop / enable a service",
            "Read service logs",
            "Check service status",
          ],
          keyTerms: ["systemctl", "journalctl", "service"],
          practiceQuestions: 3,
        },
      ],
    },
    {
      id: "lx-net",
      title: "Networking (intro)",
      emoji: "🌐",
      description: "Just enough Linux networking for DevOps.",
      lessons: [
        {
          id: "lx-net-01",
          level: "intermediate",
          title: "ping, curl, ss",
          description: "Prove something is reachable.",
          objectives: [
            "Check a host is up",
            "Make an HTTP request with curl",
            "List open ports",
          ],
          keyTerms: ["ping", "curl", "ss", "netstat"],
          practiceQuestions: 4,
        },
        {
          id: "lx-net-02",
          level: "advanced",
          title: "ssh basics",
          description: "Remote login done right.",
          objectives: [
            "Connect with ssh user@host",
            "Generate an SSH key pair",
            "Use ~/.ssh/config",
          ],
          keyTerms: ["ssh", "ssh-keygen", "authorized_keys"],
          practiceQuestions: 3,
        },
      ],
    },
    {
      id: "lx-admin",
      title: "System Admin",
      emoji: "🛠️",
      description: "Packages, cron, logs.",
      lessons: [
        {
          id: "lx-adm-01",
          level: "advanced",
          title: "Package managers",
          description: "apt vs. yum/dnf.",
          objectives: [
            "Install, update, remove packages",
            "Understand repositories",
            "Pin versions when needed",
          ],
          keyTerms: ["apt", "dnf", "yum", "dpkg", "rpm"],
          practiceQuestions: 3,
        },
        {
          id: "lx-adm-02",
          level: "advanced",
          title: "cron & logs",
          description: "Scheduling and troubleshooting.",
          objectives: [
            "Write a crontab entry",
            "Find and tail /var/log files",
            "Rotate logs with logrotate (intro)",
          ],
          keyTerms: ["cron", "crontab", "/var/log", "logrotate"],
          practiceQuestions: 3,
        },
      ],
    },
  ],
};
