import { Code2 } from "lucide-react";
import type { Topic } from "../types";
import { pythonTutor } from "../prompts/python-tutor";

export const pythonTopic: Topic = {
  id: "python",
  slug: "python",
  name: "Python / פייתון",
  description:
    "Python fundamentals, from your first variable to a working project.",
  track: "python",
  icon: Code2,
  accent: {
    gradient: "from-blue-500 to-yellow-500",
    text: "text-blue-600",
    ring: "ring-blue-500/30",
  },
  tutor: pythonTutor,
  modules: [
    {
      id: "py-variables",
      title: "Variables & I/O / משתנים וקלט-פלט",
      emoji: "🟦",
      description:
        "What a variable is, primitive types, printing, reading input.",
      lessons: [
        {
          id: "py-var-01",
          level: "beginner",
          title: "What is a variable?",
          description: "Names, assignment, memory mental model.",
          objectives: [
            "Explain what a variable is and why we need one",
            "Assign values and reassign them",
            "Read a variable with print()",
          ],
          keyTerms: ["variable", "assignment (=)", "print()", "identifier"],
          practiceQuestions: 4,
        },
        {
          id: "py-var-02",
          level: "beginner",
          title: "Primitive types & type()",
          description: "int, float, str, bool and how to inspect them.",
          objectives: [
            "Identify the type of a literal",
            "Convert between int, float, str",
            "Understand truthy / falsy basics",
          ],
          keyTerms: ["int", "float", "str", "bool", "type()"],
          practiceQuestions: 5,
        },
        {
          id: "py-var-03",
          level: "beginner",
          title: "Input & casting",
          description: "Reading stdin with input() and converting to numbers.",
          objectives: [
            "Use input() to read text",
            "Cast input to int or float when needed",
            "Format output with f-strings",
          ],
          keyTerms: ["input()", "int()", "float()", "f-string"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "py-data",
      title: "Data Types & Collections / טיפוסים ואוספים",
      emoji: "🧺",
      description: "Strings in depth, lists, tuples, sets, dicts.",
      lessons: [
        {
          id: "py-data-01",
          level: "beginner",
          title: "Strings in depth",
          description: "Indexing, slicing, methods, immutability.",
          objectives: [
            "Index and slice strings",
            "Use .upper / .lower / .find / .replace / .split / .join",
            "Explain why strings are immutable",
          ],
          keyTerms: ["slice", "index", ".split()", ".join()", "immutable"],
          practiceQuestions: 5,
        },
        {
          id: "py-data-02",
          level: "beginner",
          title: "Lists",
          description: "Creation, indexing, common methods.",
          objectives: [
            "Create and modify lists",
            "Use append, pop, sort, reverse, slicing",
            "Iterate with for",
          ],
          keyTerms: ["list", ".append()", ".pop()", ".sort()", "slice"],
          practiceQuestions: 5,
        },
        {
          id: "py-data-03",
          level: "intermediate",
          title: "Tuples, sets, dicts",
          description: "When to use each and how they differ.",
          objectives: [
            "Choose the right collection for a task",
            "Use set operations (union, intersection)",
            "Iterate dicts with .items()",
          ],
          keyTerms: ["tuple", "set", "dict", ".keys()", ".values()", ".items()"],
          practiceQuestions: 6,
        },
      ],
    },
    {
      id: "py-flow",
      title: "Control Flow / תנאים ולולאות",
      emoji: "🔀",
      description: "if/elif/else, for, while, break, continue.",
      lessons: [
        {
          id: "py-flow-01",
          level: "beginner",
          title: "Conditions",
          description: "if, elif, else, boolean operators.",
          objectives: [
            "Build if / elif / else trees",
            "Combine conditions with and, or, not",
            "Avoid common nesting pitfalls",
          ],
          keyTerms: ["if", "elif", "else", "and", "or", "not"],
          practiceQuestions: 5,
        },
        {
          id: "py-flow-02",
          level: "beginner",
          title: "Loops",
          description: "for + range(), while, break, continue.",
          objectives: [
            "Iterate with for x in …",
            "Know when to use while vs. for",
            "Use break / continue responsibly",
          ],
          keyTerms: ["for", "range()", "while", "break", "continue"],
          practiceQuestions: 6,
        },
      ],
    },
    {
      id: "py-functions",
      title: "Functions / פונקציות",
      emoji: "🧩",
      description: "Writing reusable building blocks.",
      lessons: [
        {
          id: "py-fn-01",
          level: "intermediate",
          title: "Defining functions",
          description: "def, parameters, return, default args.",
          objectives: [
            "Define and call functions",
            "Use default and keyword arguments",
            "Return one value vs. multiple",
          ],
          keyTerms: ["def", "return", "parameter", "argument"],
          practiceQuestions: 5,
        },
        {
          id: "py-fn-02",
          level: "intermediate",
          title: "Scope & recursion",
          description: "Local vs. global, and how recursion really works.",
          objectives: [
            "Identify local vs. global variables",
            "Write a simple recursive function",
            "Recognise infinite-recursion traps",
          ],
          keyTerms: ["scope", "global", "recursion", "base case"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "py-oop",
      title: "Object-Oriented Programming / OOP",
      emoji: "🏛️",
      description: "Classes, instances, inheritance.",
      lessons: [
        {
          id: "py-oop-01",
          level: "intermediate",
          title: "Classes & instances",
          description: "class, __init__, methods, attributes.",
          objectives: [
            "Define a class with __init__",
            "Create instances and call methods",
            "Understand self",
          ],
          keyTerms: ["class", "__init__", "self", "method", "attribute"],
          practiceQuestions: 5,
        },
        {
          id: "py-oop-02",
          level: "advanced",
          title: "Inheritance & dunders",
          description: "Extending classes, __str__, __eq__, __len__.",
          objectives: [
            "Extend a parent class",
            "Override methods with super()",
            "Implement a few dunder methods",
          ],
          keyTerms: ["inheritance", "super()", "__str__", "__eq__"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "py-fileio",
      title: "File I/O & Exceptions / קבצים וחריגות",
      emoji: "📄",
      description: "Reading and writing files safely.",
      lessons: [
        {
          id: "py-fi-01",
          level: "intermediate",
          title: "Reading & writing files",
          description: "open(), modes, context managers.",
          objectives: [
            "Open a file with 'with'",
            "Read line-by-line and whole file",
            "Write text safely",
          ],
          keyTerms: ["open()", "with", "read()", "write()"],
          practiceQuestions: 4,
        },
        {
          id: "py-fi-02",
          level: "intermediate",
          title: "Exceptions",
          description: "try, except, raise, custom exceptions.",
          objectives: [
            "Catch specific exceptions",
            "Use finally / else",
            "Raise your own exception",
          ],
          keyTerms: ["try", "except", "raise", "Exception"],
          practiceQuestions: 4,
        },
      ],
    },
    {
      id: "py-libs",
      title: "Libraries & Tooling / ספריות וסביבה",
      emoji: "📚",
      description: "Standard library, pip, virtualenv.",
      lessons: [
        {
          id: "py-lib-01",
          level: "intermediate",
          title: "Standard library essentials",
          description: "math, random, datetime, os.",
          objectives: [
            "Import modules",
            "Use math / random / datetime",
            "Browse the stdlib confidently",
          ],
          keyTerms: ["import", "math", "random", "datetime"],
          practiceQuestions: 4,
        },
        {
          id: "py-lib-02",
          level: "advanced",
          title: "pip & virtual environments",
          description: "Installing 3rd-party packages, venv basics.",
          objectives: [
            "Create a venv",
            "Install and pin dependencies",
            "Understand why we isolate envs",
          ],
          keyTerms: ["pip", "venv", "requirements.txt"],
          practiceQuestions: 3,
        },
      ],
    },
    {
      id: "py-projects",
      title: "Projects / פרויקטים",
      emoji: "🚀",
      description: "Putting it all together in real projects.",
      lessons: [
        {
          id: "py-proj-01",
          level: "advanced",
          title: "A CLI tool",
          description: "Argparse-driven tool with file I/O.",
          objectives: [
            "Parse CLI arguments",
            "Structure a project into modules",
            "Handle errors gracefully",
          ],
          keyTerms: ["argparse", "__main__", "sys.argv"],
          practiceQuestions: 3,
        },
        {
          id: "py-proj-02",
          level: "advanced",
          title: "A small data script",
          description: "Parsing CSV, transforming rows, writing a report.",
          objectives: [
            "Read CSV with the csv module",
            "Aggregate and summarise",
            "Write formatted output",
          ],
          keyTerms: ["csv", "dict", "aggregate"],
          practiceQuestions: 3,
        },
      ],
    },
  ],
};
