-- ============================================================
-- Issue: P0 — Audit and enforce Supabase RLS on all tables
--
-- This migration closes the remaining RLS gaps identified in
-- the security audit:
--
--   • user_learning_progress  — previously had a fully permissive
--     policy (USING (true)) that let any authenticated user read
--     or write every row.  Replaced with role-split policies:
--     authenticated users are isolated to their own rows;
--     the anon role retains a permissive policy to support
--     anonymous learners whose user_id is a client-generated
--     UUID that does not exist in auth.users.
--
--   • user_topic_completions  — same permissive policy gap, same
--     fix applied.
--
-- All other user-owned tables were audited and are already
-- covered by tight policies from earlier migrations:
--
--   user_profiles            — 20260411000001_user_profiles.sql
--   user_progress            — 20260415000002_harden_rls_policies.sql
--   topic_progress           — 20260415000010_topic_progress.sql
--   user_xp / user_streaks
--   user_milestones
--   user_onboarding          — 20260415000003_gamification_xp_streaks.sql
--   user_xp_events           — 20260415000003_gamification_xp_streaks.sql
--   exam_results             — 20260415000002_harden_rls_policies.sql
--   curriculum_question_attempts — 20260415000002_harden_rls_policies.sql
--
-- Read-only public tables (no user_id column, global data):
--   topics, questions        — public SELECT, no user-data filter needed
--   curriculum_*             — RLS enabled, read-only for authenticated
--   ai_explanation_cache     — RLS enabled, read-only for authenticated
--   question_candidates      — RLS enabled, writes service-role only
-- ============================================================

-- ---------------------------------------------------------------------------
-- 1. user_learning_progress — tighten per-role policies
--
-- The user_id column is TEXT (not UUID) to support both Supabase auth UIDs
-- and anonymous UUIDs generated by getAnonUserId() on the client.  For
-- authenticated users we cast auth.uid() to text for the equality check.
-- ---------------------------------------------------------------------------

-- Remove the previous catch-all permissive policy.
drop policy if exists "user_learning_progress_own" on public.user_learning_progress;

-- Authenticated users can only read/write their own rows.
create policy "Authenticated users see own learning progress"
  on public.user_learning_progress
  for all
  to authenticated
  using  (auth.uid()::text = user_id)
  with check (auth.uid()::text = user_id);

-- Anonymous learners retain full access so localStorage-backed flows keep
-- working.  The anon role has no identity to check against, so application
-- code is responsible for always filtering by the client-generated user_id.
create policy "Anon users see own learning progress"
  on public.user_learning_progress
  for all
  to anon
  using  (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 2. user_topic_completions — tighten per-role policies
--
-- Identical rationale: user_id is TEXT, split anon / authenticated.
-- ---------------------------------------------------------------------------

-- Remove the previous catch-all permissive policy.
drop policy if exists "user_topic_completions_own" on public.user_topic_completions;

-- Authenticated users can only read/write their own rows.
create policy "Authenticated users see own topic completions"
  on public.user_topic_completions
  for all
  to authenticated
  using  (auth.uid()::text = user_id)
  with check (auth.uid()::text = user_id);

-- Anonymous learners retain full access.
create policy "Anon users see own topic completions"
  on public.user_topic_completions
  for all
  to anon
  using  (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 3. Revoke broad public grants on user-owned tables (defence-in-depth)
--    Ensures that even if RLS is accidentally disabled, the public role
--    cannot read or write user data.
-- ---------------------------------------------------------------------------

revoke all on public.user_learning_progress from public;
revoke all on public.user_topic_completions  from public;

grant select, insert, update, delete on public.user_learning_progress to anon, authenticated;
grant select, insert, update, delete on public.user_topic_completions  to anon, authenticated;
