-- ============================================================
-- Issue: Add indexes, tighten RLS, and optimize Supabase queries
--
-- Changes:
--   1. Additional composite indexes for frequently-queried paths
--   2. Enable RLS on user_learning_progress (missing from original migration)
--   3. get_dashboard_data(p_user_id) RPC — replaces multiple round-trips
--   4. upsert_user_progress(...)     RPC — atomic read+increment, fixes N+1
-- ============================================================

-- ---------------------------------------------------------------------------
-- 1. Additional indexes
-- ---------------------------------------------------------------------------

-- user_progress: composite index accelerates "all rows for this user+topic"
-- queries used by the dashboard and practice page.
create index if not exists idx_user_progress_user_topic
  on user_progress(user_id, topic_id);

-- user_progress: composite index accelerates correct-answer count aggregation.
create index if not exists idx_user_progress_user_correct
  on user_progress(user_id, is_correct);

-- questions: filtering by difficulty and question_type is common in the
-- adaptive selector and exam-mode sampling.
create index if not exists idx_questions_difficulty
  on questions(difficulty);

create index if not exists idx_questions_question_type
  on questions(question_type);

create index if not exists idx_questions_created_at
  on questions(created_at);

-- curriculum_question_attempts: time-range and per-question lookups.
create index if not exists idx_curriculum_attempts_answered_at
  on curriculum_question_attempts(answered_at);

create index if not exists idx_curriculum_attempts_user_question
  on curriculum_question_attempts(user_id, question_id);

-- ---------------------------------------------------------------------------
-- 2. Enable RLS on user_learning_progress
--    The original migration (20260409000001) created the table but omitted RLS.
--
--    Security model (intentional, consistent with user_topic_completions):
--    The user_id column stores plain text values — both Supabase auth UUIDs
--    and anonymous UUIDs generated by getAnonUserId() on the client. Because
--    auth.uid() returns a uuid type and the column is text, an equality check
--    would require a cast and still cannot serve anonymous learners.
--
--    Row isolation is therefore enforced at the application layer: every
--    query filters with .eq("user_id", myId). The permissive policy keeps
--    RLS enabled (blocking unauthenticated direct SQL access) while allowing
--    the Supabase client (anon + authenticated roles) to operate.
-- ---------------------------------------------------------------------------

alter table user_learning_progress enable row level security;

drop policy if exists "user_learning_progress_own" on user_learning_progress;
create policy "user_learning_progress_own"
  on user_learning_progress
  for all
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 3. get_dashboard_data — single RPC that returns all user-specific data
--    needed by the dashboard in one round-trip:
--      • learning  : user_learning_progress rows (topic_id, concept_index)
--      • topic_counts : question count per topic_id (static, all users)
-- ---------------------------------------------------------------------------

create or replace function get_dashboard_data(p_user_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_learning     jsonb;
  v_topic_counts jsonb;
begin
  -- Completed concept indices per topic
  select coalesce(jsonb_agg(row_to_json(r)), '[]'::jsonb)
  into v_learning
  from (
    select topic_id, concept_index
    from user_learning_progress
    where user_id = p_user_id
  ) r;

  -- Question count aggregated per topic (used by dashboard topic cards)
  select coalesce(
    jsonb_object_agg(topic_id::text, cnt),
    '{}'::jsonb
  )
  into v_topic_counts
  from (
    select topic_id, count(*) as cnt
    from questions
    group by topic_id
  ) r;

  return jsonb_build_object(
    'learning',     v_learning,
    'topic_counts', v_topic_counts
  );
end;
$$;

revoke all on function get_dashboard_data(text) from public;
grant execute on function get_dashboard_data(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. upsert_user_progress — atomic INSERT … ON CONFLICT DO UPDATE
--    Eliminates the two-query read-then-write pattern in useRemoteProgress
--    (syncAnswerMutation). The increment is now a single DB call.
--
--    Returns jsonb { attempts, answered_at } so the caller can update its
--    optimistic cache without a second round-trip.
-- ---------------------------------------------------------------------------

create or replace function upsert_user_progress(
  p_user_id     uuid,
  p_question_id uuid,
  p_topic_id    uuid,
  p_is_correct  boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attempts integer;
  v_at       timestamptz := now();
begin
  insert into user_progress (
    user_id, question_id, topic_id, is_correct, answered_at, attempts, last_attempted_at
  ) values (
    p_user_id, p_question_id, p_topic_id, p_is_correct, v_at, 1, v_at
  )
  on conflict (user_id, question_id)
  do update set
    is_correct        = excluded.is_correct,
    answered_at       = excluded.answered_at,
    attempts          = user_progress.attempts + 1,
    last_attempted_at = excluded.last_attempted_at
  returning attempts into v_attempts;

  return jsonb_build_object(
    'attempts',    v_attempts,
    'answered_at', v_at
  );
end;
$$;

revoke all on function upsert_user_progress(uuid, uuid, uuid, boolean) from public;
grant execute on function upsert_user_progress(uuid, uuid, uuid, boolean) to anon, authenticated;
